---
# Lint Ansible playbooks
ansible-lint:
  image: registry.gitlab.com/contain-yourself/ansible-lint
  stage: test
  script:
    # This little cheat will return all of the .yml or .yaml files in the top-level directory (excluding hidden ones)
    # and will assume that these are all Ansible playbooks to be linted.
    - for i in $(find . -maxdepth 1 -not -path '*/\.*' -name "*.yml" -or -name "*.yaml"); do echo "Linting ${i}"; ansible-lint "${i}"; echo "Finished with return code $?"; done

# Lint all YAML files in this repo (any yaml file, recursively)
yaml-lint:
  image: registry.gitlab.com/contain-yourself/yamllint
  stage: test
  script:
    - for i in $(find . -name "*.yml" -or -name "*.yaml"); do echo "Linting ${i}"; yamllint "${i}"; echo "Finished with return code $?"; done
...
